spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${RESUME_REDIS_HOST}
      port: ${RESUME_REDIS_PORT}
    mongodb:
      uri: mongodb://${RESUME_MONGO_DB_USERNAME}:${RESUME_MONGO_DB_PORT}/${RESUME_MONGO_DB_DATABASE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LIKE_MYSQL_DB_HOST}:${LIKE_MYSQL_DB_PORT}/${LIKE_MYSQL_DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LIKE_MYSQL_DB_USERNAME}
    password: ${LIKE_MYSQL_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true





  jwt:
    secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: gitfolio
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

jwt:
  refreshToken:
    expiry: 86400000


server:
  port: 8082
