spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb://${RESUME_MONGO_DB_USERNAME}:${RESUME_MONGO_DB_PORT}/${RESUME_MONGO_DB_DATABASE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LIKE_MYSQL_DB_HOST}:${LIKE_MYSQL_DB_PORT}/${LIKE_MYSQL_DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LIKE_MYSQL_DB_USERNAME}
    password: ${LIKE_MYSQL_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST1}:${KAFKA_PORT1}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jwt:
    secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: gitfolio
      url-prefix: ${S3_URL_PREFIX}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

jwt:
  refreshToken:
    expiry: ${REFRESH_TOKEN_EXPIRY}

github:
  api:
    url: https://api.github.com
    token: ${GH_API_TOKEN}
member:
  server:
    url: ${MEMBER_SERVER_URL}
kakao:
  api:
    url: ${KAKAO_API_URL}
ai:
  server:
    url: ${AI_SERVER_URL}
notification:
  server:
    url: ${NOTIFICATION_SERVER_URL}

server:
  port: ${RESUME_SERVER_PORT}

redis:
  host: ${RESUME_REDIS_HOST}
  port: ${RESUME_REDIS_PORT}