spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gitfolio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_DB_HOST}:3306/${MYSQL_DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB
      resolve-lazily: true

  jwt:
    secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: gitfolio
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

server:
  port: 8081
