spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb://${MEMBER_MONGO_DB_USERNAME}:${MEMBER_MONGO_DB_PORT}/${MEMBER_MONGO_DB_DATABASE}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MEMBER_MYSQL_DB_HOST}:${MEMBER_MYSQL_DB_PORT}/${MEMBER_MYSQL_DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MEMBER_MYSQL_DB_USERNAME}
    password: ${MEMBER_MYSQL_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB
      max-file-size: 30MB
      resolve-lazily: true

  jwt:
    secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: gitfolio
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

github:
  api:
    url: https://api.github.com
    token: ${GITHUB_API_TOKEN}

jwt:
  refreshToken:
    expiry: ${REFRESH_TOKEN_EXPIRY}

server:
  port: ${MEMBER_SERVER_PORT}
grpc:
  port: ${MEMBER_GRPC_PORT}