spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${PAYMENT_MYSQL_DB_HOST}:${PAYMENT_MYSQL_DB_PORT}/${PAYMENT_MYSQL_DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${PAYMENT_MYSQL_DB_USERNAME}
    password: ${PAYMENT_MYSQL_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

  kafka:
    bootstrap-servers: ${KAFKA_HOST1}:${KAFKA_PORT1}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"

  jwt:
    secret: ${JWT_SECRET_KEY}

jwt:
  refreshToken:
    expiry: ${REFRESH_TOKEN_EXPIRY}

cloud:
  aws:
    s3:
      bucket: gitfolio
      url-prefix: ${S3_URL_PREFIX}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

server:
  port: ${PAYMENT_SERVER_PORT}

kakaopay:
  secretKey: ${KAKAOPAY_SECRET_KEY}
  cid: TCSUBSCRIP

payment:
  server:
    url: ${PAYMENT_SERVER_URL}

github:
  api:
    url: https://api.github.com
    token: ${GH_API_TOKEN}
member:
  server:
    url: ${MEMBER_SERVER_URL}
kakao:
  api:
    url: ${KAKAO_API_URL}
ai:
  server:
    url: ${AI_SERVER_URL}