FROM amazoncorretto:17 AS runner
WORKDIR /notification
EXPOSE 8080

COPY --from=aida0/gitfolio_builder:jenkins /gitfolio_back/build/.env .env
COPY --from=aida0/gitfolio_builder:jenkins /gitfolio_back/build/*-notification-*-SNAPSHOT.jar notification.jar

CMD [ "java", "-jar", "notification.jar" ]