spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          github:
            client-name: GitHub
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/github"
            authorization-grant-type: authorization_code
            scope: read:user
  datasource:
    url: none

  jwt:
    secret: ${JWT_SECRET_KEY}


  data:
    redis:
      host: ${AUTH_REDIS_HOST}
      port: ${AUTH_REDIS_PORT}

cloud:
  aws:
    s3:
      bucket: gitfolio
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

server:
  port: ${AUTH_SERVER_PORT}

jwt:
  refreshToken:
    expiry: ${REFRESH_TOKEN_EXPIRY}
  accessToken:
    expiry: ${ACCESS_TOKEN_EXPIRY}
  redirect:
    mainPageUrl: ${REDIRECT_MAIN_URL}
    onBoardingPageUrl: ${REDIRECT_ONBOARDING_URL}

member:
  server:
    url: ${MEMBER_SERVER_URL}
