spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          github:
            client-name: GitHub
            client-id: ${GH_CLIENT_ID}
            client-secret: ${GH_CLIENT_SECRET}
            redirect-uri: ${GH_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: read:user
  datasource:
    url: none
  data:
    redis:
      host: ${RESUME_REDIS_HOST}
      port: ${RESUME_REDIS_PORT}

  jwt:
    secret: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: gitfolio
      url-prefix: ${S3_URL_PREFIX}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

server:
  port: ${AUTH_SERVER_PORT}

jwt:
  refreshToken:
    expiry: ${REFRESH_TOKEN_EXPIRY}
  accessToken:
    expiry: ${ACCESS_TOKEN_EXPIRY}
  redirect:
    mainPageUrl: ${REDIRECT_MAIN_URL}
    onBoardingPageUrl: ${REDIRECT_ONBOARDING_URL}

member:
  server:
    url: ${MEMBER_SERVER_URL}
github:
  api:
    url: https://api.github.com
kakao:
  api:
    url: ${KAKAO_API_URL}
ai:
  server:
    url: ${AI_SERVER_URL}