name: Dev CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [gitfolio-auth, gitfolio-member, gitfolio-payment, gitfolio-resume]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 (Amazon Corretto)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build module
        run: ./gradlew :${{ matrix.module }}:clean :${{ matrix.module }}:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.module }}
          file: ./${{ matrix.module }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.module }}:latest
          build-args: |
            JAR_FILE=build/libs/${{ matrix.module }}-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            modules=(gitfolio-auth gitfolio-member gitfolio-payment gitfolio-resume)
            for module in "${modules[@]}"; do
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${module}:latest
              docker stop ${module} || true
              docker rm ${module} || true
              case $module in
                gitfolio-auth)
                  docker run -d --name ${module} -p 8081:8081 ${{ secrets.DOCKERHUB_USERNAME }}/${module}:latest
                  ;;
                gitfolio-member)
                  docker run -d --name ${module} -p 8082:8082 ${{ secrets.DOCKERHUB_USERNAME }}/${module}:latest
                  ;;
                gitfolio-payment)
                  docker run -d --name ${module} -p 8083:8083 ${{ secrets.DOCKERHUB_USERNAME }}/${module}:latest
                  ;;
                gitfolio-resume)
                  docker run -d --name ${module} -p 8084:8084 ${{ secrets.DOCKERHUB_USERNAME }}/${module}:latest
                  ;;
              esac
            done