name: Backend MSA CI/CD Pipeline

on:
  push:
    branches:
      - 48-Develop브랜치-푸시시-CI/CD-구현

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Builder 이미지 빌드 및 캐시 활용
      - name: Build and push builder image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          target: builder
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gitfolio_builder:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/gitfolio_builder:latest
          cache-to: type=inline

      # 각 서비스별 이미지 빌드 및 푸시
      - name: Build and push service images
        run: |
          services=("auth" "member" "payment" "resume")
          for service in "${services[@]}"; do
            docker build \
              --platform linux/amd64 \
              --build-arg BUILDER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/gitfolio_builder:latest \
              -f ./gitfolio-${service}/dockerfile \
              --target runner \
              -t ${{ secrets.DOCKERHUB_USERNAME }}/gitfolio_${service}:latest \
              ./gitfolio-${service}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitfolio_${service}:latest
          done

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: gitfolio-auth
            port: 8080
            instance_tag: "Gitfolio BE auth"
          - module: gitfolio-member
            port: 8081
            instance_tag: "Gitfolio BE member"
          - module: gitfolio-payment
            port: 8083
            instance_tag: "Gitfolio BE payment"
          - module: gitfolio-resume
            port: 8082
            instance_tag: "Gitfolio BE resume"

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Get EC2 instance ID
        id: get-instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters \
              "Name=tag:Service,Values=back" \
              "Name=tag:Module,Values=member" \
              "Name=tag:Name,Values=${{ matrix.instance_tag }}" \
              "Name=tag:Environment,Values=dev" \
              "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text)
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT

      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Deploy to EC2 using SSM
        run: |
          aws ssm start-session \
            --target "${{ steps.get-instance.outputs.instance_id }}" \
            --document-name AWS-StartInteractiveCommand \
            --parameters command="\
              sudo -i && \
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} && \
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.module }}:latest && \
              docker stop ${{ matrix.module }} || true && \
              docker rm ${{ matrix.module }} || true && \
              docker run -d \
                --name ${{ matrix.module }} \
                -p ${{ matrix.port }}:8080 \
                -e MEMBER_SERVER_URL=http://\${MEMBER_PRIVATE_IP}:8081 \
                -e AUTH_SERVER_URL=http://\${AUTH_PRIVATE_IP}:8080 \
                -e RESUME_SERVER_URL=http://\${RESUME_PRIVATE_IP}:8082 \
                -e PAYMENT_SERVER_URL=http://\${PAYMENT_PRIVATE_IP}:8083 \
                ${{ secrets.DOCKERHUB_USERNAME }}/gitfolio_${matrix.module#gitfolio-}:latest"