name: Backend MSA CI/CD Pipeline

on:
  push:
    branches:
      - 48-Develop브랜치-푸시시-CI/CD-구현

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: gitfolio-auth
            port: 8080
            service_name: auth
            instance_name: "Gitfolio BE1"
            instance_index: "1"
          - module: gitfolio-member
            port: 8081
            service_name: member
            instance_name: "Gitfolio BE1"
            instance_index: "1"
          - module: gitfolio-payment
            port: 8083
            service_name: payment
            instance_name: "Gitfolio BE2"
            instance_index: "2"
          - module: gitfolio-resume
            port: 8082
            service_name: resume
            instance_name: "Gitfolio BE2"
            instance_index: "2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push service image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.module }}
          file: ./${{ matrix.module }}/dockerfile
          platforms: linux/amd64
          push: true
          tags: aida0/gitfolio_${{ matrix.service_name }}:test
          build-args: |
            BUILDER_IMAGE=aida0/gitfolio_builder:test

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: gitfolio-auth
            port: 8080
            service_name: auth
            instance_name: "Gitfolio BE1"
            instance_index: "1"
          - module: gitfolio-member
            port: 8081
            service_name: member
            instance_name: "Gitfolio BE1"
            instance_index: "1"
          - module: gitfolio-payment
            port: 8083
            service_name: payment
            instance_name: "Gitfolio BE2"
            instance_index: "2"
          - module: gitfolio-resume
            port: 8082
            service_name: resume
            instance_name: "Gitfolio BE2"
            instance_index: "2"

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Get EC2 instance ID
        id: get-instance
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters \
              "Name=tag:Service,Values=back" \
              "Name=tag:Environment,Values=dev" \
              "Name=tag:Name,Values=${{ matrix.instance_name }}" \
              "Name=tag:Index,Values=${{ matrix.instance_index }}" \
              "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].InstanceId" \
            --output text)
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT

      - name: Install Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Deploy to EC2 using SSM
        run: |
          aws ssm start-session \
            --target "${{ steps.get-instance.outputs.instance_id }}" \
            --document-name "AWS-StartInteractiveCommand" \
            --parameters '{
              "command": ["sudo -i && docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} && docker pull aida0/gitfolio_${{ matrix.service_name }}:test && docker stop gitfolio_${{ matrix.service_name }} || true && docker rm gitfolio_${{ matrix.service_name }} || true && docker run -d --name gitfolio_${{ matrix.service_name }} -p ${{ matrix.port }}:8080 -e MEMBER_SERVER_URL=https://${MEMBER_PRIVATE_IP}:8081 -e AUTH_SERVER_URL=https://${AUTH_PRIVATE_IP}:8080 -e RESUME_SERVER_URL=https://${RESUME_PRIVATE_IP}:8082 -e PAYMENT_SERVER_URL=https://${PAYMENT_PRIVATE_IP}:8083 aida0/gitfolio_${{ matrix.service_name }}:test"]
            }'